mainSections = ["posts", "docs", "blogs"]
mobileNavigation = "right" # Mobile nav menu will open to the left of the screen.
numberOfTagsShown = 20 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy
enableSearch = true

showReadTime=false
showShare=false
showRelatedInArticle = true
showRelatedInSidebar = true
numberOfRecentPosts = 6
pinFeatured = true
numberOfFeaturedPosts = 10

dateFormat = "2006-01-02"