[[main]]
  name = "시리즈"
  url = "series/"
  weight = -110
[[main]]
  parent = "시리즈"
  name = "LinkedIn"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "시리즈"
  name = "Twitter"
  url = "https://twitter.com/"


# social menu links
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/chankoo"
